info = {
    "enzymes": "If the enzyme is microbial or plant-based, it is considered halal. If it is animal-based, like rennet, it is only halal provided that the animal itself is halal and the way it was slaughtered is halal.",
    "whey": "Rennet, the enzyme used to make whey, can come from an animal which is either not halal or was not slaughtered in a halal way.",
    "lard": "Lard is derived from pigs, which are haram.",
    "meat": "If the meat comes from an animal which is not halal or which was not slaughtered in a halal way, then it is considered haram to consume that meat.",
    "bacon": "Bacon is made from pork, which is haram.",
    "pepperoni": "Pepperoni is almost always made out of pork, which is haram. If it is made from beef, then it is only halal provided that the way the cow was slaughtered is halal.",
    "pork": "Pork is haram.",
    "ham": "Ham is made from pork, which is haram.",
    "chicken": "If the chicken was not slaughtered in a halal way, then it is considered haram to consume its meat.",
    "beef": "If the cow was not slaughtered in a halal way, then it is considered haram to consume its meat.",
    "lamb": "If the lamb was not slaughtered in a halal way, then it is considered haram to consume its meat.",
    "goat": "If the goat was not slaughtered in a halal way, then it is considered haram to consume its meat.",
    "gelatin": "If the gelatin comes from an animal which is not halal or which was not slaughtered in a halal way, then it is considered haram.",
    "rennet": "If it is derived from an animal which is either not halal or was not slaughtered in a halal way, then it is considered haram.",
    "l-cysteine": "If it is sourced from fish, microbial, or plant-based materials, it is considered halal. If it is animal-based, it is only halal provided that the animal itself is halal and the way it was slaughtered is halal.",
    "pepsin": "If it is derived from an animal which is either not halal or was not slaughtered in a halal way, then it is considered haram.",
    "alcohol": "Alcohol is haram.",
    "ethanol": "Ethanol is an intoxicant, which makes it haram.",
    "vanilla extract": "Since vanilla extract contains alcohol, it is considered haram.",
    "wine vinegar": "Wine vinegar is made by fermenting wine, which is haram.",
    "malt extract": "Due to its alcohol association and use of enzymes which might come from non-halal sources, it is mostly considered haram.",
    "monoglycerides": "If it is derived from an animal which is either not halal or was not slaughtered in a halal way, then it is considered haram.",
    "diglycerides": "If it is derived from an animal which is either not halal or was not slaughtered in a halal way, then it is considered haram.",
    "e471": "If it is derived from an animal which is either not halal or was not slaughtered in a halal way, then it is considered haram.",
    "glycerin": "If it is derived from an animal which is either not halal or was not slaughtered in a halal way, then it is considered haram.",
    "glycerol": "If it is derived from an animal which is either not halal or was not slaughtered in a halal way, then it is considered haram.",
    "e422": "If it is derived from an animal which is either not halal or was not slaughtered in a halal way, then it is considered haram.",
    "shortening": "If it is derived from an animal which is either not halal or was not slaughtered in a halal way, then it is considered haram.",
    "magensium stearate": "If the stearic acid is derived from an animal which is either not halal or was not slaughtered in a halal way, then it is considered haram.",
    "carmine": "Carmine is a red pigment extracted from cochineal insect, which is considered impure or filthy, and therefore haram.",
    "e120": "Carmine is a red pigment extracted from cochineal insect, which is considered impure or filthy, and therefore haram.",
}
